# March Machine Learning Mania 2026 Japanese Tutorial (日本語チュートリアル)

## コンペティション概要
毎年恒例の“March Madness（全米大学バスケのトーナメント）” を題材に、2026年の男子・女子トーナメントの勝敗を確率で予測する予測コンペです。提出は「勝つ／負ける」ではなく、あらゆる対戦カードに対して “あるチームが勝つ確率” を出す形式です（確率予測）。2026年の実際のトーナメントが行われてからスコアが確定する（＝開催前はスコアが反映されにくい）という性質があり、手元での検証設計が重要になります。

---

### 課題設定・目的

1. 目的は、「TeamId が小さい方（low）が、大きい方（high）に勝つ確率」を、対象となる全対戦について予測して提出することです。男子・女子の両方が対象で、提出IDは 2026_TeamIdLow_TeamIdHigh のような形式で与えられます。


2. 評価は **Brier score（確率予測の平均二乗誤差：予測確率と実際の0/1のMSE）**で行われます。直感的には「勝つ確率0.7と言った試合は、長期的に7割勝っていてほしい」という“確率の素直さ（較正）”を問う指標です。

3. コンペデータは、当年シーズンの途中時点（例：2月上旬）まで整備済みで、シーズンが進むにつれて更新される旨が説明されています。

---

### モチベーションとチャレンジ点

- 番狂わせが起きやすいトーナメントを、確率としてどれだけ上手く見積もれるか、という点がこのシリーズの魅力です。男子・女子の両方を扱うので、同じ枠組み（Elo、レーティング、効率指標、シードなど）をどこまで一般化できるかが腕の見せ所になります。

- 「確率を当てる」難しさ（分類ではなく確率推定）。0/1を当てるより、0.58と言った試合の妥当性”が問われます（Brier score）。そのため、AUCのような順位指標の感覚で進めるとズレやすく、**較正（calibration）**が効いてきます。

- 検証（CV）の設計が難しい：時間・シーズン依存。スポーツ予測は年ごとに環境が揺れます。さらに本番は2026年なので、ローカル検証は過去年（例：2022–2025）をどう使うかが肝になります。

- リーダーボードの扱いが独特（本番が“未来”にある）。2026年の試合が終わるまでスコアが確定しない性質があり、提出の見え方・運用が通常の即時スコア型コンペと違います（例：スコアが0.0表示になる旨の注意など）。

- 提出運用の落とし穴。「スコア対象にする提出を選ぶ」必要がある、など運用上の注意が示されています。

---

## 準備

In [2]:
# ライブラリーインポート
#　基本的ライブラリー
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from IPython.display import display
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

# ディスプレイオプション
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Set professional plotting style
plt.style.use('ggplot')
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['font.family'] = 'Arial'
custom_palette = ["#3498db", "#e74c3c", "#2ecc71", "#f39c12", "#9b59b6"]
sns.set_palette(custom_palette)

## 提供データの構成

### Data Section 1 「基本のデータ」
このセクションでは、簡単な予測モデルを構築し、予測を送信するために必要なものがすべて提供されている。

- **MTeams.csv, WTeams.csv** : チームの情報
- **MSeasons.csv, WSeasons.csv** : 履歴データに含まれる様々な季節と、特定の季節レベルのプロパティ。
- **MNCAATourneySeeds.csv, WNCAATourneySeeds.csv** : 過去の全シーズンにおけるNCAA®トーナメントの全チームのシード順
- **MRegularSeasonCompactResults.csv, WRegularSeasonCompactResults.csv**: 複数シーズンにわたる歴史的データの試合ごとの結果
- **MNCAATourneyCompactResults.csv, WNCAATourneyCompactResults.csv** : NCAA®トーナメントの全シーズンの試合結果
- **SampleSubmissionStage1.csv, SampleSubmissionStage2.csv** : 提出ファイルのフォーマット

### Data Section 2 「チームボックススコア」
このセクションでは2003年シーズン(男子)または2010年シーズン(女子)以降のすべてのレギュラーシーズン、カンファレンストーナメント、NCAA®トーナメントゲームについて、チームレベルのゲームごとの統計(フリースローの試合投数、ディフェンスリバウンド、ターンオーバーなど)が示されている。

- **MRegularSeasonDetailedResults.csv, WRegularSeasonDetailedResults.csv** : レギュラーシーズンの履歴データにおけるチームレベルのボックススコア
- **MNCAATourneyDetailedResults.csv, WNCAATourneyDetailedResults.csv** : NCAA®トーナメントのチームレベルのボックススコア

### Data Section 3 「開催地域」
このセクションでは、2010 年シーズン以降のすべてのレギュラー シーズン、カンファレンス トーナメント、NCAA® トーナメントの都市での開催場所が示されている。

- **Cities.csv** : これまで試合が開催された都市のマスターリスト
- **MGameCities.csv, WGameCities.csv** : 試合と、試合が行われた都市

### Data Section 4 「公開ランキング」
このセクションでは、2003年シーズン以降の数十のトップ評価システム（ポメロイ、サガリン、RPI、ESPNなど）の毎週のチームランキング（男子チームのみ）が提供されている。

- **MMasseyOrdinals.csv** : 男子チームの順位（例：1位、2位、3位、…、N位）が、様々なランキングシステムを用いてリストアップされている。

### Data Section 5 「補足情報」
このセクションには、コーチ、カンファレンス所属、チーム名の代替スペル、ブラケット構造、NIT およびその他のポストシーズン トーナメントのゲーム結果などの追加の補足情報が含まれている。

- **MTeamCoaches.csv** : 各チームの各シーズンのヘッドコーチが記載されており、シーズン途中のコーチ交代を示すDayNumの開始/終了範囲も含まれている。
- **Conferences.csv** : このファイルは、1985年以降に存在したディビジョンIカンファレンスの一覧
- **MTeamConferences.csv, WTeamConferences.csv** : 各チームのシーズン中のカンファレンス所属
- **MConferenceTourneyGames.csv, WConferenceTourneyGames.csv** : 各年のポストシーズン男子および女子カンファレンス トーナメント 
- **MSecondaryTourneyTeams.csv, WSecondaryTourneyTeams.csv** : NCAA®トーナメント以外のポストシーズンの男子または女子トーナメントに参加したチームの識別
- **MSecondaryTourneyCompactResults.csv, WSecondaryTourneyCompactResults.csv** : 「セカンダリー」ポストシーズントーナメントのトーナメント戦の最終スコア
- **MTeamSpellings.csv, WTeamSpellings.csv** : 多くのチーム名の代替スペル
- **MNCAATourneySlots.csv, WNCAATourneySlots.csv** : トーナメントのラウンドが進むにつれて、シードに応じてチーム同士が対戦するメカニズムの識別
- **MNCAATourneySeedRoundSlots.csv** : 特定のトーナメントシードにおいて、各試合ラウンドでどのブラケットスロットでプレーするか、そしてそのラウンドのDayNum値が何になるか

## 簡易的データ観察

In [3]:
# データ読み込み
BASE_DIR = Path("./")
INPUT_DIR = Path(BASE_DIR / "data")
OUTPUT_DIR = Path(BASE_DIR / "output")
# BASE_DIR = "/kaggle/input/march-machine-learning-mania-2026"

# Data Section 1
Teams_M_df = pl.read_csv(INPUT_DIR / "MTeams.csv")
Teams_W_df = pl.read_csv(INPUT_DIR / "WTeams.csv")
Seasons_M_df = pl.read_csv(INPUT_DIR / "MSeasons.csv")
Seasons_W_df = pl.read_csv(INPUT_DIR / "WSeasons.csv")
NCAATourneySeeds_M_df = pl.read_csv(INPUT_DIR / "MNCAATourneySeeds.csv")
NCAATourneySeeds_W_df = pl.read_csv(INPUT_DIR / "WNCAATourneySeeds.csv")
RegularSeasonCompactResults_M_df = pl.read_csv(INPUT_DIR / "MRegularSeasonCompactResults.csv")
RegularSeasonCompactResults_W_df = pl.read_csv(INPUT_DIR / "WRegularSeasonCompactResults.csv")
NCAATourneyCompactResults_M_df = pl.read_csv(INPUT_DIR / "MNCAATourneyCompactResults.csv")
NCAATourneyCompactResults_W_df = pl.read_csv(INPUT_DIR / "WNCAATourneyCompactResults.csv")
SampleSubmissionStage1_df = pl.read_csv(INPUT_DIR / "SampleSubmissionStage1.csv")
SampleSubmissionStage2_df = pl.read_csv(INPUT_DIR / "SampleSubmissionStage2.csv")

In [4]:
# 生データ観察
print("row data Teams")
display(Teams_M_df.head())
display(Teams_W_df.head())

row data Teams

shape: (5, 4)
┌────────┬─────────────┬───────────────┬──────────────┐
│ TeamID ┆ TeamName    ┆ FirstD1Season ┆ LastD1Season │
│ ---    ┆ ---         ┆ ---           ┆ ---          │
│ i64    ┆ str         ┆ i64           ┆ i64          │
╞════════╪═════════════╪═══════════════╪══════════════╡
│ 1101   ┆ Abilene Chr ┆ 2014          ┆ 2026         │
│ 1102   ┆ Air Force   ┆ 1985          ┆ 2026         │
│ 1103   ┆ Akron       ┆ 1985          ┆ 2026         │
│ 1104   ┆ Alabama     ┆ 1985          ┆ 2026         │
│ 1105   ┆ Alabama A&M ┆ 2000          ┆ 2026         │
└────────┴─────────────┴───────────────┴──────────────┘

shape: (5, 2)
┌────────┬─────────────┐
│ TeamID ┆ TeamName    │
│ ---    ┆ ---         │
│ i64    ┆ str         │
╞════════╪═════════════╡
│ 3101   ┆ Abilene Chr │
│ 3102   ┆ Air Force   │
│ 3103   ┆ Akron       │
│ 3104   ┆ Alabama     │
│ 3105   ┆ Alabama A&M │
└────────┴─────────────┘

### カラム詳細(データ.csv)

In [5]:
print("row data Seasons")
display(Seasons_M_df.head())
display(Seasons_W_df.head())

row data Seasons

shape: (5, 6)
┌────────┬────────────┬─────────┬───────────┬───────────┬───────────┐
│ Season ┆ DayZero    ┆ RegionW ┆ RegionX   ┆ RegionY   ┆ RegionZ   │
│ ---    ┆ ---        ┆ ---     ┆ ---       ┆ ---       ┆ ---       │
│ i64    ┆ str        ┆ str     ┆ str       ┆ str       ┆ str       │
╞════════╪════════════╪═════════╪═══════════╪═══════════╪═══════════╡
│ 1985   ┆ 10/29/1984 ┆ East    ┆ West      ┆ Midwest   ┆ Southeast │
│ 1986   ┆ 10/28/1985 ┆ East    ┆ Midwest   ┆ Southeast ┆ West      │
│ 1987   ┆ 10/27/1986 ┆ East    ┆ Southeast ┆ Midwest   ┆ West      │
│ 1988   ┆ 11/02/1987 ┆ East    ┆ Midwest   ┆ Southeast ┆ West      │
│ 1989   ┆ 10/31/1988 ┆ East    ┆ West      ┆ Midwest   ┆ Southeast │
└────────┴────────────┴─────────┴───────────┴───────────┴───────────┘

shape: (5, 6)
┌────────┬────────────┬─────────┬─────────┬─────────┬─────────┐
│ Season ┆ DayZero    ┆ RegionW ┆ RegionX ┆ RegionY ┆ RegionZ │
│ ---    ┆ ---        ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ i64    ┆ str        ┆ str     ┆ str     ┆ str     ┆ str     │
╞════════╪════════════╪═════════╪═════════╪═════════╪═════════╡
│ 1998   ┆ 10/27/1997 ┆ East    ┆ Midwest ┆ Mideast ┆ West    │
│ 1999   ┆ 10/26/1998 ┆ East    ┆ Mideast ┆ Midwest ┆ West    │
│ 2000   ┆ 11/01/1999 ┆ East    ┆ Midwest ┆ Mideast ┆ West    │
│ 2001   ┆ 10/30/2000 ┆ East    ┆ Midwest ┆ Mideast ┆ West    │
│ 2002   ┆ 10/29/2001 ┆ East    ┆ West    ┆ Mideast ┆ Midwest │
└────────┴────────────┴─────────┴─────────┴─────────┴─────────┘

### カラム詳細(データ.csv)

In [6]:
print("row data NCAATourneySeeds")
display(NCAATourneySeeds_M_df.head())
display(NCAATourneySeeds_W_df.head())

row data NCAATourneySeeds

shape: (5, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1985   ┆ W01  ┆ 1207   │
│ 1985   ┆ W02  ┆ 1210   │
│ 1985   ┆ W03  ┆ 1228   │
│ 1985   ┆ W04  ┆ 1260   │
│ 1985   ┆ W05  ┆ 1374   │
└────────┴──────┴────────┘

shape: (5, 3)
┌────────┬──────┬────────┐
│ Season ┆ Seed ┆ TeamID │
│ ---    ┆ ---  ┆ ---    │
│ i64    ┆ str  ┆ i64    │
╞════════╪══════╪════════╡
│ 1998   ┆ W01  ┆ 3330   │
│ 1998   ┆ W02  ┆ 3163   │
│ 1998   ┆ W03  ┆ 3112   │
│ 1998   ┆ W04  ┆ 3301   │
│ 1998   ┆ W05  ┆ 3272   │
└────────┴──────┴────────┘

### カラム詳細(データ.csv)

In [7]:
print("row data RegularSeasonCompactResults")
display(RegularSeasonCompactResults_M_df.head())
display(RegularSeasonCompactResults_W_df.head())

row data RegularSeasonCompactResults

shape: (5, 8)
┌────────┬────────┬─────────┬────────┬─────────┬────────┬──────┬───────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ LTeamID ┆ LScore ┆ WLoc ┆ NumOT │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---     ┆ ---    ┆ ---  ┆ ---   │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆ i64     ┆ i64    ┆ str  ┆ i64   │
╞════════╪════════╪═════════╪════════╪═════════╪════════╪══════╪═══════╡
│ 1985   ┆ 20     ┆ 1228    ┆ 81     ┆ 1328    ┆ 64     ┆ N    ┆ 0     │
│ 1985   ┆ 25     ┆ 1106    ┆ 77     ┆ 1354    ┆ 70     ┆ H    ┆ 0     │
│ 1985   ┆ 25     ┆ 1112    ┆ 63     ┆ 1223    ┆ 56     ┆ H    ┆ 0     │
│ 1985   ┆ 25     ┆ 1165    ┆ 70     ┆ 1432    ┆ 54     ┆ H    ┆ 0     │
│ 1985   ┆ 25     ┆ 1192    ┆ 86     ┆ 1447    ┆ 74     ┆ H    ┆ 0     │
└────────┴────────┴─────────┴────────┴─────────┴────────┴──────┴───────┘

shape: (5, 8)
┌────────┬────────┬─────────┬────────┬─────────┬────────┬──────┬───────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ LTeamID ┆ LScore ┆ WLoc ┆ NumOT │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---     ┆ ---    ┆ ---  ┆ ---   │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆ i64     ┆ i64    ┆ str  ┆ i64   │
╞════════╪════════╪═════════╪════════╪═════════╪════════╪══════╪═══════╡
│ 1998   ┆ 18     ┆ 3104    ┆ 91     ┆ 3202    ┆ 41     ┆ H    ┆ 0     │
│ 1998   ┆ 18     ┆ 3163    ┆ 87     ┆ 3221    ┆ 76     ┆ H    ┆ 0     │
│ 1998   ┆ 18     ┆ 3222    ┆ 66     ┆ 3261    ┆ 59     ┆ H    ┆ 0     │
│ 1998   ┆ 18     ┆ 3307    ┆ 69     ┆ 3365    ┆ 62     ┆ H    ┆ 0     │
│ 1998   ┆ 18     ┆ 3349    ┆ 115    ┆ 3411    ┆ 35     ┆ H    ┆ 0     │
└────────┴────────┴─────────┴────────┴─────────┴────────┴──────┴───────┘

### カラム詳細(データ.csv)

In [8]:
print("row data NCAATourneyCompactResults")
display(NCAATourneyCompactResults_M_df.head())
display(NCAATourneyCompactResults_W_df.head())

row data NCAATourneyCompactResults

shape: (5, 8)
┌────────┬────────┬─────────┬────────┬─────────┬────────┬──────┬───────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ LTeamID ┆ LScore ┆ WLoc ┆ NumOT │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---     ┆ ---    ┆ ---  ┆ ---   │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆ i64     ┆ i64    ┆ str  ┆ i64   │
╞════════╪════════╪═════════╪════════╪═════════╪════════╪══════╪═══════╡
│ 1985   ┆ 136    ┆ 1116    ┆ 63     ┆ 1234    ┆ 54     ┆ N    ┆ 0     │
│ 1985   ┆ 136    ┆ 1120    ┆ 59     ┆ 1345    ┆ 58     ┆ N    ┆ 0     │
│ 1985   ┆ 136    ┆ 1207    ┆ 68     ┆ 1250    ┆ 43     ┆ N    ┆ 0     │
│ 1985   ┆ 136    ┆ 1229    ┆ 58     ┆ 1425    ┆ 55     ┆ N    ┆ 0     │
│ 1985   ┆ 136    ┆ 1242    ┆ 49     ┆ 1325    ┆ 38     ┆ N    ┆ 0     │
└────────┴────────┴─────────┴────────┴─────────┴────────┴──────┴───────┘

shape: (5, 8)
┌────────┬────────┬─────────┬────────┬─────────┬────────┬──────┬───────┐
│ Season ┆ DayNum ┆ WTeamID ┆ WScore ┆ LTeamID ┆ LScore ┆ WLoc ┆ NumOT │
│ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---     ┆ ---    ┆ ---  ┆ ---   │
│ i64    ┆ i64    ┆ i64     ┆ i64    ┆ i64     ┆ i64    ┆ str  ┆ i64   │
╞════════╪════════╪═════════╪════════╪═════════╪════════╪══════╪═══════╡
│ 1998   ┆ 137    ┆ 3104    ┆ 94     ┆ 3422    ┆ 46     ┆ H    ┆ 0     │
│ 1998   ┆ 137    ┆ 3112    ┆ 75     ┆ 3365    ┆ 63     ┆ H    ┆ 0     │
│ 1998   ┆ 137    ┆ 3163    ┆ 93     ┆ 3193    ┆ 52     ┆ H    ┆ 0     │
│ 1998   ┆ 137    ┆ 3198    ┆ 59     ┆ 3266    ┆ 45     ┆ H    ┆ 0     │
│ 1998   ┆ 137    ┆ 3203    ┆ 74     ┆ 3208    ┆ 72     ┆ A    ┆ 0     │
└────────┴────────┴─────────┴────────┴─────────┴────────┴──────┴───────┘

### カラム詳細(データ.csv)

In [9]:
print("row data SampleSubmissionStage")
display(SampleSubmissionStage1_df.head())
display(SampleSubmissionStage2_df.head())

row data SampleSubmissionStage

shape: (5, 2)
┌────────────────┬──────┐
│ ID             ┆ Pred │
│ ---            ┆ ---  │
│ str            ┆ f64  │
╞════════════════╪══════╡
│ 2022_1101_1102 ┆ 0.5  │
│ 2022_1101_1103 ┆ 0.5  │
│ 2022_1101_1104 ┆ 0.5  │
│ 2022_1101_1105 ┆ 0.5  │
│ 2022_1101_1106 ┆ 0.5  │
└────────────────┴──────┘

shape: (5, 2)
┌────────────────┬──────┐
│ ID             ┆ Pred │
│ ---            ┆ ---  │
│ str            ┆ f64  │
╞════════════════╪══════╡
│ 2026_1101_1102 ┆ 0.5  │
│ 2026_1101_1103 ┆ 0.5  │
│ 2026_1101_1104 ┆ 0.5  │
│ 2026_1101_1105 ┆ 0.5  │
│ 2026_1101_1106 ┆ 0.5  │
└────────────────┴──────┘

### カラム詳細(データ.csv)

## EDA

## データ考察と戦略立案

## モデル構築と予測

今回使用する予測モデルは

## 性能評価
### 評価手法の解説

## 再考察

## コメント

### 最後に
ここまで読んでいただきありがとうございました。私はデータ分析の学習のためにkaggleのコンペティションに参加しています。何かアドバイスや疑問点があればお気軽にコメントしてください。日本語でも英語でもどちらでも対応しています。...

参考

参考文献タイトル: 
[参考文献URL]

参考文献タイトル: 
[参考文献URL]

参考文献タイトル: 
[参考文献URL]